@startuml Web訪問者システムクラス図

skinparam classAttributeIconSize 0

class 訪問者 {
    '属性
    - ユーザID
    - パスワード
    - 名前
    - 学校名
    - 所属名
    - メールアドレス
    - 電話番号
    - 年齢

    '操作
    + 新規登録する()
    + ログインする()
    + ログアウトする()
    + 自分と他の人の情報を参照する()
    + 自分の情報を変更する()
    + 自分の情報を削除する()
}

@enduml