@startuml 会議室予約システムドメインモデル図
skinparam componentStyle rectangle

' 会議室予約システム
[会議室予約システム] o-- [ユーザー]
[会議室予約システム] o-- [ログイン]
[会議室予約システム] o-- [ログアウト]
[会議室予約システム] o-- [会議室]
[会議室予約システム] o-- [予約]

[ユーザー] o-- [ユーザーID]
[ユーザー] o-- [ユーザー名]

[会議室] o-- [会議室名]
[会議室] o-- [座席数]
[会議室] o-- [AV機器の有無]

[予約] <|-- [予約番号]

[予約番号] o-- [利用会議室]
[予約番号] o-- [利用時刻]
[予約番号] o-- [利用目的]

@enduml