@startuml ユースケース図_共通システム_注文
left to right direction

actor ユーザー as User
actor 管理者 as Admin

rectangle 共通システム_注文 {
    usecase "注文を作成する" as UC1
    usecase "注文を参照する" as UC2
    usecase "注文を更新する" as UC3
    usecase "注文をキャンセルする" as UC4
}

User --> UC1
User --> UC2
User --> UC3
User --> UC4

Admin --> UC2


@enduml