@startuml ユースケース図_共通システム_発送
left to right direction

actor ユーザー as User
actor 管理者 as Admin

rectangle 共通システム_発送 {
    usecase "発送情報を登録する" as UC1
    usecase "発送情報を参照する" as UC2
    usecase "発送状況を更新する" as UC3
}

User --> UC2

Admin --> UC1
Admin --> UC2
Admin --> UC3

@enduml